### ISSUE TITLE
Unable to specify a collins configuration when using `collins.NewClientFromYaml`

### ISSUE THREAD

**Issue by alex-laties** [tumblr/go-collins#2]
There are times when I wish to specify which config file I'd like to use.

Rather than having `collins.NewClientFromYaml()` always search for a config file, I'd like to pass it a filepath that it will parse.

**Comment by schallert** [comment]
Is there some situation you've encountered where setting [`COLLINS_CLIENT_CONFIG`](https://github.com/tumblr/go-collins/blob/4c6091cc1d7dd647302ec5c4901906ec6dead84a/collins/collins.go#L160) isn't sufficient? If there seems to be a good use case then adding this feature sounds like a good idea to me. And if so I'd rather we did it without making any breaking API changes, so by adding a new function that accepted a path rather than changing the signature of `NewClientFromYaml`.

**Comment by alex-laties** [comment]
Hey @schallert, yes. The situation would be when you need to connect to more than one Collins instance.

The equivalent feature is provided in `Collins::Authenticator.setup_client`.

I can understand not wanting to change the signature for `NewClientFromYaml`.

It sounds like a new function is needed. Something along the lines of `NewClientFromPath` or `NewClientFromFile`.

**Comment by defect** [comment]
Yup, definitely sounds like a sane addition. How about something like this: https://github.com/tumblr/go-collins/compare/master...defect:newclient_from_path ? Then you could just pass a single-element array to `NewClientFromFiles()`.

NB: I haven't actually tested the code above :) If it seems sane I'll write up a couple of unit tests for it and make a proper PR.

**Comment by alex-laties** [comment]
yeah, that seems remarkably reasonable to me
